server:
  port: 8080
spring:
  datasource:
    platform: oracle
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: REDENVELOPE
    password: GHDQKDH
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true